### ISSUE TITLE
Use album cover when the song doesn't have an image

### ISSUE THREAD

**Issue by LouisH-760** [m0ngr31/jellyamp#1]
For some songs, I have an album image at the album level, but not at the song level. As such, the album has a cover displayed but playing a song shows no cover. Maybe in this case pulling the album image might help?

Thank you for the otherwise great app!

**Comment by m0ngr31** [comment]
I'd have to investigate that. Would be worth looking into.

**Comment by Maxplosion** [comment]
I would also appreciate this feature!
