### ISSUE TITLE
Media Controls in Taskbar

### ISSUE THREAD

**Issue by Maxplosion** [m0ngr31/jellyamp#10]
(Might be more down the line, regarding the Windows 10 version)
Would it be possible to get media controls in the taskbar popup window so we can control Play/Pause + Next/Back.

As an example, foobar2000 does it too like this: 
![pic1](https://user-images.githubusercontent.com/9304484/91883538-dd3fb700-ec84-11ea-8365-fe67c33058af.jpg)

**Comment by m0ngr31** [comment]
I'll have to research this. I don't have a Windows machine, so it'll take me a minute

**Comment by Maxplosion** [comment]
No hurries, it's really **not** an important feature!

**Comment by m0ngr31** [comment]
For reference:
https://www.electronjs.org/docs/tutorial/windows-taskbar#thumbnail-toolbars
https://stackoverflow.com/questions/35876939/frameless-window-with-controls-in-electron-windows
https://felixrieseberg.com/using-native-windows-features-from-electron/
