### ISSUE TITLE
arm build

### ISSUE THREAD

**Issue by jorge-aparicio** [m0ngr31/jellyamp#12]
Would releasing an arm build of jellyamp in the form of an AppImage be possible? The UI of JellyAmp looks like it would be perfect for the PinePhone/Librem 5 and would also make the application available to users on devices such as the PineBook, PineTab, Raspberry Pi and other Linux ARM devices. Thanks for your work!

**Comment by m0ngr31** [comment]
I'll have to look into this.

**Comment by m0ngr31** [comment]
I updated the CI to push out an ARM64 appimage next time there is a release.
