### ISSUE TITLE
No Log Out After Password Change

### ISSUE THREAD

**Issue by crash5545** [m0ngr31/jellyamp#13]
I changed the password on my account and suspect that has caused my instance of jellyamp to no longer show any of my music. There are no present options to log out or notifications that it failed to log in. Uninstalling and reinstalling jellyamp does not remove log in information and doesn't appear in any obvious location for editing or deleting. 

![Capture](https://user-images.githubusercontent.com/7400007/94185604-5da7a100-fe5a-11ea-971c-81a2530b40fa.PNG)

**Comment by m0ngr31** [comment]
If you follow the steps from this ticket, you can resolve this issue: https://github.com/m0ngr31/jellyamp/issues/9

**Comment by m0ngr31** [comment]
But I'm going to make a settings page where you can logout manually.

**Comment by m0ngr31** [comment]
This is done now.
