### ISSUE TITLE
[Request] Be able to change playback bitrate

### ISSUE THREAD

**Issue by m0ngr31** [m0ngr31/jellyamp#17]
^^^^

**Comment by nv4** [comment]
This may be broken. In Jellyamp settings I put the bitrate at 320 (tried lower options too), but it has no effect, even after restarting the app. Jellyfin server dashboard reports it's still direct streaming in FLAC at full bitrate.

By contrast, when I set a lower bitrate on the official web player, the dashboard reports transcode streaming in AAC at the lower rate. So I'm almost certain it's an issue with this app not the server.

**Comment by m0ngr31** [comment]
It might be how I'm reporting it to the server. You can look at the bandwidth usage and see the difference pretty easily.
