### ISSUE TITLE
Odd centering on "home" page...

### ISSUE THREAD

**Issue by Fabeuss** [m0ngr31/jellyamp#2]
![image](https://user-images.githubusercontent.com/40515597/86441202-1e126280-bd0c-11ea-8889-4bc6f2314cd0.png)

(Appimage on Ubuntu 20.04)

**Comment by studio315b** [comment]
This also repros on Manjaro KDE

**Comment by DuncanBennie** [comment]
Can confirm that I also experienced this on macOS 10.15.5.

**Comment by m0ngr31** [comment]
Does this always happen or just randomly?

**Comment by studio315b** [comment]
This appears to happen every time for me

**Comment by m0ngr31** [comment]
I wonder if it's a scaling thing?

**Comment by m0ngr31** [comment]
I just had it happen to me and I'm creating a new release now
