### ISSUE TITLE
[Request] Permit switching to album view on the home page

### ISSUE THREAD

**Issue by orakless** [m0ngr31/jellyamp#23]
Instead of "Artist", would be better to just let the user choose between Artist, Genre, Album, etc on the home page. Maybe "Last listened" or "Recently added" could be great too.

**Comment by nv4** [comment]
Yes PLEASE add this, idgaf about artists view, I want to see my album covers lol

**Comment by m0ngr31** [comment]
I'll add this next

**Comment by m0ngr31** [comment]
Will be released with v1.1.0.
