### ISSUE TITLE
[Question] Update available notification

### ISSUE THREAD

**Issue by sandervankasteel** [m0ngr31/jellyamp#24]
Hi! First off, awesome work on JellyAmp! I use it on a nearly daily basis 😄 

I was wondering, would you accept an PR with where a notification would be shown if a newer release of JellyAmp is available on Github ?

**Comment by m0ngr31** [comment]
Just a notification or auto-upgrade? I've avoided auto-upgrade because it's not supported on all binaries...

**Comment by sandervankasteel** [comment]
Just a notification :smile:

**Comment by m0ngr31** [comment]
Yeah, that sounds great

**Comment by m0ngr31** [comment]
Will be released with v1.1.0.
