### ISSUE TITLE
[Request] Add to end of queue (instead of "play next")

### ISSUE THREAD

**Issue by lmnewkirk** [m0ngr31/jellyamp#30]
Is it possible to add a button/option so that instead of injecting the songs into the queue so that they play next, they instead get appended to the end of the queue? I often like to queue up several albums to play in a row and that requires either being able to append to the end of the queue or adding the songs individually (which isn't worth the effort)

**Comment by m0ngr31** [comment]
Yeah, that's pretty easy - good request!

**Comment by lmnewkirk** [comment]
Thanks! And thanks for all the work on the app, it's been really nice to have a lightweight desktop player for my music!

**Comment by m0ngr31** [comment]
Will be released with v1.1.0
