### ISSUE TITLE
Cannot scale back up with Ctrl +

### ISSUE THREAD

**Issue by a-rekkusu** [m0ngr31/jellyamp#31]
I can scale the view / DPI lower using `Ctrl -  ` but not up again using `Ctrl +`
System is Fedora 33 Workstation in X11 Gnome session on a Lenovo Thinkpad Laptop.
I'm using the v 1.0 AppImage.

**Comment by m0ngr31** [comment]
I'll look into this. In the meantime, you can press `Ctrl 0` and it'll reset it

**Comment by m0ngr31** [comment]
It looks like for electron, you need to push `Ctrl Shift +`...

**Comment by m0ngr31** [comment]
Fixed in v1.1.0
