### ISSUE TITLE
Seeking not working on songs added to the queue

### ISSUE THREAD

**Issue by Sanderstarr** [m0ngr31/jellyamp#33]
When adding a song to the queue seeking to different parts of the song doesn't work.
But when just selecting play song it works just fine.
Something I found that might have to do something with this is that the song added to the queue has a duration of 0:00

**Comment by m0ngr31** [comment]
I can confirm, I'll fix it. Good find, thanks!

**Comment by m0ngr31** [comment]
Fixed in v1.1.1
