### ISSUE TITLE
Feature request: m4a (Lossless) support for macOS

### ISSUE THREAD

**Issue by stefan1983** [m0ngr31/jellyamp#39]
Hey there,

just tried the app on my MacBook Pro without any success.

I am running a macOS Big Sur 11.6 and get an error message with every track I try to play:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/8542806/141777219-3d56489b-96bc-4102-8d5c-946f915b5836.png">

The music files are mainly in M4A format.

**Comment by stefan1983** [comment]
As I just found out, MP3 files are working so far. So seems to be missing m4a (Lossless) support.
Anything planned so far?

**Comment by m0ngr31** [comment]
Have you tried the transcode setting to see if that will force it to work?

**Comment by stefan1983** [comment]
Nope, but after converting them to FLAC they work fine.
