### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by alexanderadam** [m0ngr31/jellyamp#4]
Thank you for jellyamp!

I wasn't able to [find jellyamp on F-Droid](https://search.f-droid.org/?q=jelly) yet so I thought it would be great if jellyamp could get a release there.

I'm not related to F-Droid but they have [a good FAQ page](https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included).

I know that there's already [Gelli coming into F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6755) but Jellyamp looks much cleaner so far.

**Comment by m0ngr31** [comment]
It's not on F-Droid since it's not an Android app. I was able to get it "running" on Android with [Capacitor](https://capacitorjs.com/), but it's not a great experience. I don't have the time to get it working better at this time since Gelli already runs great.

**Comment by alexanderadam** [comment]
Okay, thank you for your explanation.
