### ISSUE TITLE
Artwork does not display correctly in fullscreen mode

### ISSUE THREAD

**Issue by itsthejoker** [m0ngr31/jellyamp#40]
On every screen that has artwork on it, every image is tiled over the one before it by roughly a third. See the below screenshot for an example in an artist view, but the issue appears on every screen. You can also see a scroll bar appear at the bottom of the screen.

<img width="1440" alt="Screen Shot 2021-12-28 at 12 43 22 PM 2" src="https://user-images.githubusercontent.com/5179553/147593388-3d72fd63-cdda-4352-9701-8c53f536462b.png">

**Comment by m0ngr31** [comment]
How are you making it fullscreen? It would take some effort for the styles to work properly at something other than the default application window.

**Comment by itsthejoker** [comment]
Sorry, I just found your reply. 
![image](https://user-images.githubusercontent.com/5179553/170715944-0c7eaba1-5f8c-467b-84fe-a2d22cfd52ee.png)

I'll go ahead and close this if it's not the intended usage.
