### ISSUE TITLE
macOS Traffic Lights are overlayed w/ electron ones

### ISSUE THREAD

**Issue by michaelhthomas** [m0ngr31/jellyamp#5]
Issue: macOS adds it's own traffic lights, on top of bit slightly offset from the ones built into the application
![image](https://user-images.githubusercontent.com/18223295/86968399-1f8fc080-c13a-11ea-8dcf-68d2dd71959f.png)
To reproduce: Open the app on macOS and use window controls
Also, it appears as though both sets of buttons do indeed function as intended.

**Comment by m0ngr31** [comment]
New release will be fixing this and media control support on macOS this afternoon!
