### ISSUE TITLE
Unable to use 

### ISSUE THREAD

**Issue by PMCJTM** [m0ngr31/jellyamp#9]
When opening after first installing I don't have the option to add a server and am instead met with the below screen
![Jellyamp_HxSWTa2ff2](https://user-images.githubusercontent.com/50344976/89144943-2cc38380-d51d-11ea-88a7-5405d0b74c73.png)

**Comment by m0ngr31** [comment]
Windows or Linux?

**Comment by PMCJTM** [comment]
Windows

**Comment by m0ngr31** [comment]
You should be able to push "Ctrl-Shift-i` and see the inspector. Inside of that is a `Console` tab. You should see the error there. My best guess without seeing the error is that there is a name collision on the localstorage keys I'm using for saving user data.

I'm going to namespace Jellyamp and we'll see if that fixes it for you.

**Comment by PMCJTM** [comment]
When I do open the console tab this is what I see
![Jellyamp_bc3rsSvefk](https://user-images.githubusercontent.com/50344976/89345283-247e5c00-d675-11ea-8be9-2b36fc869523.png)

**Comment by m0ngr31** [comment]
If you click on the vertical 3 dots, you can break out the inspector window.

<img width="229" alt="image" src="https://user-images.githubusercontent.com/1045977/89346129-1130b800-d698-11ea-9d54-a1e96a3f5418.png">

That should make it a little easier to debug. Go to the `Application` tab and click on `Local Storage`. You can clear out the settings for the app and then if you re-launch it should work.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/1045977/89346250-41785680-d698-11ea-8276-4de861830406.png">

I need to make a check for expired API tokens...

**Comment by PMCJTM** [comment]
It worked, thank you.

**Comment by m0ngr31** [comment]
👍

**Comment by m0ngr31** [comment]
Added some code to check for expired tokens and have you login again if that happens.
